// ============================================================
// OpportunityX — development seed data
// Dummy identities only. All emails use .local domains.
// All values conform to the actual Mongoose schemas in
// backend/src/models/. Nothing here is real personal data.
// ============================================================

const SEED_PASSWORD = "Seed@12345";

const SEED_ADMINS = [
  { name: "Admin Seed", email: "admin.seed@opportunityx.local" },
  { name: "Aisha Kapoor", email: "admin02@opportunityx.local" },
];

const SEED_RECRUITERS = [
  {
    name: "Recruiter Seed",
    email: "recruiter.seed@opportunityx.local",
    companyName: "NovaTech Solutions",
    verificationStatus: "verified",
  },
  {
    name: "Vikram Malhotra",
    email: "recruiter02@opportunityx.local",
    companyName: "ByteCraft Labs",
    verificationStatus: "verified",
  },
  {
    name: "Sneha Iyer",
    email: "recruiter03@opportunityx.local",
    companyName: "CloudMatrix Technologies",
    verificationStatus: "verified",
  },
  {
    name: "Arjun Nair",
    email: "recruiter04@opportunityx.local",
    companyName: "FinEdge Systems",
    verificationStatus: "unverified",
  },
  {
    name: "Pooja Deshmukh",
    email: "recruiter05@opportunityx.local",
    companyName: "DevSphere Technologies",
    verificationStatus: "unverified",
  },
  {
    name: "Rohan Kapoor",
    email: "recruiter06@opportunityx.local",
    companyName: null,
    verificationStatus: "unverified",
  },
];

const SEED_CANDIDATES = [
  {
    name: "Aarav Sharma",
    email: "candidate01@opportunityx.local",
    phone: "9812345671",
    location: "Bengaluru, India",
    title: "Full Stack MERN Developer",
    candidateType: "experienced",
    bio: "Full stack developer with 4 years of experience building scalable web applications using the MERN stack. Passionate about clean architecture and mentoring junior developers.",
    skills: ["react", "node.js", "mongodb", "express", "typescript", "docker"],
    education: [
      { school: "IIT Delhi", degree: "B.Tech Computer Science", year: "2019" },
    ],
    experience: [
      { company: "NovaTech Solutions", role: "Full Stack Developer", duration: "2021 - Present", description: "Built and maintained MERN applications serving 50k monthly users." },
      { company: "ByteCraft Labs", role: "Frontend Developer", duration: "2019 - 2021", description: "Implemented responsive React UIs and component libraries." },
    ],
    projects: [
      { name: "RecruitFlow", url: "https://github.com/dummy/recruitflow", description: "Open source ATS built with the MERN stack." },
    ],
    certifications: [{ name: "AWS Certified Developer", issuer: "Amazon Web Services", year: "2023" }],
    socials: { linkedin: "https://linkedin.com/in/dummy-aarav", github: "https://github.com/dummy-aarav" },
    expectedSalaryMin: 1600000,
  },
  {
    name: "Riya Verma",
    email: "candidate02@opportunityx.local",
    phone: "9822345672",
    location: "Mumbai, India",
    title: "Frontend Developer (React)",
    candidateType: "experienced",
    bio: "Frontend engineer specializing in React and TypeScript with a strong eye for design systems and accessibility. 3 years of production experience.",
    skills: ["react", "typescript", "css", "tailwindcss", "next.js"],
    education: [{ school: "VJTI Mumbai", degree: "B.E. Information Technology", year: "2020" }],
    experience: [
      { company: "CloudMatrix Technologies", role: "Frontend Developer", duration: "2020 - Present", description: "Led migration of legacy UI to a React design system." },
    ],
    projects: [{ name: "DesignSystemKit", url: "", description: "Reusable component library with storybook documentation." }],
    certifications: [{ name: "Google UX Design", issuer: "Google", year: "2022" }],
    socials: { github: "https://github.com/dummy-riya" },
    expectedSalaryMin: 1300000,
  },
  {
    name: "Rahul Mehta",
    email: "candidate03@opportunityx.local",
    phone: "9832345673",
    location: "Pune, India",
    title: "Backend Developer (Node.js)",
    candidateType: "experienced",
    bio: "Backend developer focused on Node.js, MongoDB, and distributed systems. Experienced with microservices, message queues, and performance tuning.",
    skills: ["node.js", "express", "mongodb", "postgresql", "redis", "kafka"],
    education: [{ school: "COEP Pune", degree: "B.Tech Computer Engineering", year: "2018" }],
    experience: [
      { company: "FinEdge Systems", role: "Backend Developer", duration: "2019 - Present", description: "Designed APIs handling 10M requests/day with 99.9% uptime." },
    ],
    projects: [{ name: "QueueOps", url: "https://github.com/dummy/queueops", description: "Monitoring dashboard for Kafka consumer lag." }],
    certifications: [{ name: "Node.js Certified", issuer: "OpenJS Foundation", year: "2021" }],
    socials: { linkedin: "https://linkedin.com/in/dummy-rahul" },
    expectedSalaryMin: 1800000,
  },
  {
    name: "Ananya Singh",
    email: "candidate04@opportunityx.local",
    phone: "9842345674",
    location: "Delhi NCR, India",
    title: "Data Analyst",
    candidateType: "experienced",
    bio: "Data analyst skilled in SQL, Python, and visualization tools. I turn raw data into actionable business insights for product and growth teams.",
    skills: ["python", "sql", "pandas", "tableau", "power bi"],
    education: [{ school: "DU Delhi", degree: "B.Sc Statistics", year: "2019" }],
    experience: [
      { company: "CloudMatrix Technologies", role: "Data Analyst", duration: "2020 - Present", description: "Built dashboards used by leadership for weekly product decisions." },
    ],
    projects: [{ name: "SalesInsights", url: "", description: "End-to-end sales analytics pipeline." }],
    certifications: [{ name: "Google Data Analytics", issuer: "Google", year: "2021" }],
    socials: { linkedin: "https://linkedin.com/in/dummy-ananya" },
    expectedSalaryMin: 1200000,
  },
  {
    name: "Karan Patel",
    email: "candidate05@opportunityx.local",
    phone: "9852345675",
    location: "Ahmedabad, India",
    title: "Java Developer",
    candidateType: "experienced",
    bio: "Java developer with 6 years of experience in enterprise applications, Spring Boot microservices, and cloud deployments on AWS.",
    skills: ["java", "spring boot", "microservices", "aws", "mysql"],
    education: [{ school: "Nirma University", degree: "B.Tech Computer Science", year: "2017" }],
    experience: [
      { company: "ByteCraft Labs", role: "Senior Java Developer", duration: "2019 - Present", description: "Led team building payment-grade Java services." },
      { company: "FinEdge Systems", role: "Java Developer", duration: "2017 - 2019", description: "Built REST APIs for banking platforms." },
    ],
    projects: [{ name: "OrderCore", url: "", description: "Spring Boot order management system." }],
    certifications: [{ name: "Oracle Certified Java SE 11", issuer: "Oracle", year: "2020" }],
    socials: { github: "https://github.com/dummy-karan" },
    expectedSalaryMin: 2200000,
  },
  {
    name: "Priya Nair",
    email: "candidate06@opportunityx.local",
    phone: "9862345676",
    location: "Kochi, India",
    title: "UI/UX Designer",
    candidateType: "experienced",
    bio: "Product designer crafting delightful, accessible interfaces for web and mobile. Experienced in end-to-end design from research to high-fidelity prototypes.",
    skills: ["figma", "ui design", "ux research", "prototyping", "design systems"],
    education: [{ school: "NID Ahmedabad", degree: "B.Des Interaction Design", year: "2020" }],
    experience: [
      { company: "NovaTech Solutions", role: "UI/UX Designer", duration: "2021 - Present", description: "Owned design for the flagship recruitment product." },
    ],
    projects: [{ name: "TalentBoard", url: "", description: "Kanban-style interview pipeline UI." }],
    certifications: [{ name: "Certified Usability Analyst", issuer: "HFI", year: "2022" }],
    socials: { portfolio: "https://dummy-priya.design" },
    expectedSalaryMin: 1400000,
  },
  {
    name: "Aditya Rao",
    email: "candidate07@opportunityx.local",
    phone: "9872345677",
    location: "Hyderabad, India",
    title: "DevOps Engineer",
    candidateType: "experienced",
    bio: "DevOps engineer automating cloud infrastructure with Terraform and Kubernetes. Focused on CI/CD pipelines, observability, and cost optimization.",
    skills: ["aws", "terraform", "kubernetes", "docker", "ci/cd", "grafana"],
    education: [{ school: "BITS Pilani", degree: "B.E. Electronics", year: "2018" }],
    experience: [
      { company: "CloudMatrix Technologies", role: "DevOps Engineer", duration: "2019 - Present", description: "Reduced deployment time by 80% through pipeline automation." },
    ],
    projects: [{ name: "InfraAsCode", url: "https://github.com/dummy/infra", description: "Terraform modules for multi-env AWS setups." }],
    certifications: [{ name: "AWS Certified DevOps Engineer", issuer: "Amazon Web Services", year: "2023" }],
    socials: { github: "https://github.com/dummy-aditya" },
    expectedSalaryMin: 2100000,
  },
  {
    name: "Ishaan Gupta",
    email: "candidate08@opportunityx.local",
    phone: "9882345678",
    location: "Bengaluru, India",
    title: "MERN Stack Developer",
    candidateType: "fresher",
    bio: "Recent computer science graduate passionate about full stack development. Built several production-style projects with React, Node.js, and MongoDB.",
    skills: ["react", "node.js", "mongodb", "express", "javascript"],
    education: [{ school: "RV College of Engineering", degree: "B.E. Computer Science", year: "2024" }],
    experience: [],
    projects: [
      { name: "EduTrack", url: "https://github.com/dummy/edutrack", description: "Learning management platform for college courses." },
      { name: "ChatNow", url: "", description: "Realtime chat app using Socket.IO." },
    ],
    certifications: [{ name: "Meta Front-End Developer", issuer: "Meta", year: "2024" }],
    socials: { github: "https://github.com/dummy-ishaan" },
    expectedSalaryMin: 600000,
  },
  {
    name: "Meera Joshi",
    email: "candidate09@opportunityx.local",
    phone: "9892345679",
    location: "Chennai, India",
    title: "QA Engineer",
    candidateType: "experienced",
    bio: "QA engineer specializing in test automation for web applications. Experienced with Playwright, Jest, and continuous quality in CI pipelines.",
    skills: ["testing", "playwright", "jest", "cypress", "api testing"],
    education: [{ school: "Anna University", degree: "B.Tech Information Technology", year: "2019" }],
    experience: [
      { company: "ByteCraft Labs", role: "QA Engineer", duration: "2020 - Present", description: "Built automated regression suite covering 90% of critical paths." },
    ],
    projects: [{ name: "TestPilot", url: "", description: "CI-integrated test orchestration tool." }],
    certifications: [{ name: "ISTQB Foundation", issuer: "ISTQB", year: "2020" }],
    socials: { linkedin: "https://linkedin.com/in/dummy-meera" },
    expectedSalaryMin: 1100000,
  },
  {
    name: "Kabir Khan",
    email: "candidate10@opportunityx.local",
    phone: "9802345680",
    location: "Bengaluru, India",
    title: "Python Developer",
    candidateType: "experienced",
    bio: "Python developer working on backend services, data pipelines, and ML model deployment. 4 years of experience across fintech and SaaS.",
    skills: ["python", "django", "fastapi", "postgresql", "machine learning"],
    education: [{ school: "VIT Vellore", degree: "B.Tech Computer Science", year: "2019" }],
    experience: [
      { company: "FinEdge Systems", role: "Python Developer", duration: "2020 - Present", description: "Built data ingestion pipelines and REST APIs." },
    ],
    projects: [{ name: "MLScore", url: "https://github.com/dummy/mlscore", description: "Resume scoring service using NLP." }],
    certifications: [{ name: "TensorFlow Developer", issuer: "Google", year: "2022" }],
    socials: { github: "https://github.com/dummy-kabir" },
    expectedSalaryMin: 1700000,
  },
  {
    name: "Sanya Batra",
    email: "candidate11@opportunityx.local",
    phone: "9812345681",
    location: "Gurugram, India",
    title: "Cloud Engineer",
    candidateType: "experienced",
    bio: "Cloud engineer focused on AWS architecture, cost governance, and serverless systems. Enjoy building reliable, scalable cloud solutions.",
    skills: ["aws", "gcp", "serverless", "docker", "python"],
    education: [{ school: "SRM University", degree: "B.Tech Computer Science", year: "2018" }],
    experience: [
      { company: "CloudMatrix Technologies", role: "Cloud Engineer", duration: "2020 - Present", description: "Designed multi-account AWS landing zones." },
    ],
    projects: [{ name: "CloudCostGuard", url: "", description: "Serverless cost alerting system." }],
    certifications: [{ name: "Google Professional Cloud Architect", issuer: "Google", year: "2023" }],
    socials: { linkedin: "https://linkedin.com/in/dummy-sanya" },
    expectedSalaryMin: 2000000,
  },
  {
    name: "Nikhil Menon",
    email: "candidate12@opportunityx.local",
    phone: "9822345682",
    location: "Thiruvananthapuram, India",
    title: "Cybersecurity Analyst",
    candidateType: "experienced",
    bio: "Security analyst experienced in SOC operations, incident response, and vulnerability management. Certified and hands-on with SIEM tools.",
    skills: ["soc", "incident response", "siem", "penetration testing", "network security"],
    education: [{ school: "NIT Calicut", degree: "B.Tech Computer Science", year: "2019" }],
    experience: [
      { company: "CyberNest Talent", role: "Security Analyst", duration: "2020 - Present", description: "Reduced mean time to detect from days to minutes." },
    ],
    projects: [{ name: "ThreatPlaybook", url: "", description: "Internal red team playbooks." }],
    certifications: [{ name: "CompTIA Security+", issuer: "CompTIA", year: "2021" }],
    socials: { linkedin: "https://linkedin.com/in/dummy-nikhil" },
    expectedSalaryMin: 1500000,
  },
];

// Organizations + membership role assignments (recruiter emails -> org roles).
const SEED_ORGANIZATIONS = [
  {
    name: "NovaTech Hiring",
    slug: "novatech-hiring",
    ownerEmail: "recruiter.seed@opportunityx.local",
    website: "https://novatech.example.com",
    industry: "Technology",
    companySize: "201-500",
    country: "India",
    timezone: "Asia/Kolkata",
    subscriptionPlan: "growth",
    subscriptionStatus: "active",
    members: [
      { email: "recruiter.seed@opportunityx.local", role: "owner" },
      { email: "recruiter02@opportunityx.local", role: "admin" },
      { email: "recruiter03@opportunityx.local", role: "recruiter" },
      { email: "recruiter04@opportunityx.local", role: "hiring_manager" },
      { email: "recruiter05@opportunityx.local", role: "interviewer" },
      { email: "recruiter06@opportunityx.local", role: "viewer" },
    ],
    invitations: [
      { email: "recruiter02@opportunityx.local", role: "admin", status: "accepted" },
      { email: "pending.recruiter@opportunityx.local", role: "recruiter", status: "pending" },
    ],
    branding: {
      primaryColor: "#2563eb",
      careerPageHeadline: "Build the future of hiring with NovaTech",
      companyDescription: "NovaTech Solutions is a product company reshaping how teams hire.",
    },
  },
  {
    name: "ByteCraft Recruitment",
    slug: "bytecraft-recruitment",
    ownerEmail: "recruiter02@opportunityx.local",
    website: "https://bytecraft.example.com",
    industry: "Software Services",
    companySize: "51-200",
    country: "India",
    timezone: "Asia/Kolkata",
    subscriptionPlan: "starter",
    subscriptionStatus: "active",
    members: [
      { email: "recruiter02@opportunityx.local", role: "owner" },
      { email: "recruiter03@opportunityx.local", role: "admin" },
      { email: "recruiter04@opportunityx.local", role: "recruiter" },
      { email: "recruiter.seed@opportunityx.local", role: "hiring_manager" },
    ],
    invitations: [
      { email: "interviewer@opportunityx.local", role: "interviewer", status: "pending" },
    ],
    branding: { primaryColor: "#0f766e", careerPageHeadline: "Engineers hiring engineers at ByteCraft" },
  },
  {
    name: "CyberNest Talent",
    slug: "cybernest-talent",
    ownerEmail: "recruiter05@opportunityx.local",
    website: "https://cybernest.example.com",
    industry: "Cybersecurity",
    companySize: "11-50",
    country: "India",
    timezone: "Asia/Kolkata",
    subscriptionPlan: "free",
    subscriptionStatus: "trial",
    members: [
      { email: "recruiter05@opportunityx.local", role: "owner" },
      { email: "recruiter06@opportunityx.local", role: "admin" },
      { email: "recruiter03@opportunityx.local", role: "recruiter" },
    ],
    invitations: [],
    branding: { primaryColor: "#7c3aed", careerPageHeadline: "Join the team keeping the internet safe" },
  },
];

// Job category templates — expanded into full job documents during seeding.
const JOB_CATEGORIES = {
  "Frontend Developer": {
    skills: ["react", "javascript", "typescript", "css", "tailwindcss"],
    experienceLevel: "mid",
    jobType: "full-time",
    workMode: "remote",
    salary: { min: 1200000, max: 1800000 },
    location: "Bengaluru, India",
    summary: "Join a product team building polished, accessible frontends with React and TypeScript.",
    responsibilities: "Build responsive UI components; collaborate with designers; ensure web performance; write unit tests.",
    qualifications: "2+ years with React; strong JavaScript/TypeScript; experience with modern CSS.",
  },
  "React Developer": {
    skills: ["react", "redux", "javascript", "typescript", "testing"],
    experienceLevel: "mid",
    jobType: "full-time",
    workMode: "hybrid",
    salary: { min: 1100000, max: 1600000 },
    location: "Mumbai, India",
    summary: "Develop rich single-page applications with React, Redux, and a component-first architecture.",
    responsibilities: "Own React features end to end; optimize rendering; maintain component library; review PRs.",
    qualifications: "3+ years of React; solid state management experience; familiarity with testing tools.",
  },
  "MERN Developer": {
    skills: ["react", "node.js", "mongodb", "express", "javascript"],
    experienceLevel: "mid",
    jobType: "full-time",
    workMode: "remote",
    salary: { min: 1400000, max: 2000000 },
    location: "Bengaluru, India",
    summary: "Work across the full stack on a MongoDB, Express, React, and Node.js recruitment platform.",
    responsibilities: "Build REST APIs and React UIs; design MongoDB schemas; ship features independently.",
    qualifications: "Full stack MERN experience; comfortable with MongoDB aggregation and auth.",
  },
  "Backend Developer": {
    skills: ["node.js", "express", "mongodb", "redis", "api design"],
    experienceLevel: "mid",
    jobType: "full-time",
    workMode: "hybrid",
    salary: { min: 1500000, max: 2200000 },
    location: "Pune, India",
    summary: "Design and maintain scalable backend services and public APIs for a fast-growing platform.",
    responsibilities: "Build reliable REST APIs; integrate with databases and queues; improve performance.",
    qualifications: "Strong Node.js; experience with MongoDB and Redis; good API design instincts.",
  },
  "Node.js Developer": {
    skills: ["node.js", "express", "mongodb", "docker", "microservices"],
    experienceLevel: "mid",
    jobType: "full-time",
    workMode: "remote",
    salary: { min: 1400000, max: 1900000 },
    location: "Hyderabad, India",
    summary: "Build event-driven backend services on Node.js powering realtime product features.",
    responsibilities: "Write backend services; handle WebSocket traffic; monitor service health.",
    qualifications: "Proficient in Node.js; exposure to Docker and cloud platforms.",
  },
  "Full Stack Developer": {
    skills: ["react", "node.js", "mongodb", "express", "aws"],
    experienceLevel: "mid",
    jobType: "full-time",
    workMode: "hybrid",
    salary: { min: 1600000, max: 2400000 },
    location: "Bengaluru, India",
    summary: "Deliver end-to-end features spanning React frontends and Node.js backend services.",
    responsibilities: "Ship full-stack features; design data models; deploy and monitor services.",
    qualifications: "Comfortable across the stack; production deployment experience preferred.",
  },
  "Java Developer": {
    skills: ["java", "spring boot", "microservices", "mysql", "aws"],
    experienceLevel: "senior",
    jobType: "full-time",
    workMode: "onsite",
    salary: { min: 1800000, max: 2800000 },
    location: "Mumbai, India",
    summary: "Build enterprise Java services on Spring Boot for a financial technology team.",
    responsibilities: "Develop Spring Boot microservices; ensure transactional integrity; coach juniors.",
    qualifications: "5+ years Java; strong Spring ecosystem knowledge; banking domain a plus.",
  },
  "Python Developer": {
    skills: ["python", "django", "fastapi", "postgresql", "machine learning"],
    experienceLevel: "mid",
    jobType: "full-time",
    workMode: "remote",
    salary: { min: 1300000, max: 1900000 },
    location: "Bengaluru, India",
    summary: "Build Python backends and data pipelines for a data-driven hiring product.",
    responsibilities: "Develop Python services; build ETL pipelines; integrate ML services.",
    qualifications: "Strong Python; experience with Django or FastAPI; data pipeline exposure.",
  },
  "Data Analyst": {
    skills: ["sql", "python", "pandas", "tableau", "excel"],
    experienceLevel: "mid",
    jobType: "full-time",
    workMode: "hybrid",
    salary: { min: 1000000, max: 1500000 },
    location: "Delhi NCR, India",
    summary: "Turn hiring and product data into clear insights for leadership and teams.",
    responsibilities: "Build dashboards; run ad-hoc analyses; maintain data quality checks.",
    qualifications: "SQL fluency; Python or Tableau; strong communication of insights.",
  },
  "Cloud Engineer": {
    skills: ["aws", "gcp", "terraform", "docker", "kubernetes"],
    experienceLevel: "senior",
    jobType: "full-time",
    workMode: "remote",
    salary: { min: 1900000, max: 2600000 },
    location: "Bengaluru, India",
    summary: "Own cloud architecture, automation, and cost efficiency for a scaling platform.",
    responsibilities: "Design cloud infrastructure; write Terraform; operate Kubernetes clusters.",
    qualifications: "Deep AWS/GCP knowledge; IaC experience; incident response capability.",
  },
  "DevOps Engineer": {
    skills: ["aws", "docker", "kubernetes", "ci/cd", "terraform", "monitoring"],
    experienceLevel: "senior",
    jobType: "full-time",
    workMode: "remote",
    salary: { min: 1800000, max: 2500000 },
    location: "Hyderabad, India",
    summary: "Automate deployment pipelines and observability for a SaaS recruitment product.",
    responsibilities: "Manage CI/CD; improve monitoring and alerting; optimize cloud spend.",
    qualifications: "Kubernetes and Terraform experience; strong Linux skills.",
  },
  "Security Engineer": {
    skills: ["application security", "penetration testing", "aws", "owasp"],
    experienceLevel: "senior",
    jobType: "full-time",
    workMode: "hybrid",
    salary: { min: 2000000, max: 3000000 },
    location: "Bengaluru, India",
    summary: "Embed security into development, review code, and run vulnerability programs.",
    responsibilities: "Conduct security reviews; build security tooling; drive remediation.",
    qualifications: "AppSec experience; familiarity with OWASP; cloud security knowledge.",
  },
  "Cybersecurity Analyst": {
    skills: ["siem", "incident response", "network security", "vulnerability management"],
    experienceLevel: "mid",
    jobType: "full-time",
    workMode: "onsite",
    salary: { min: 1100000, max: 1600000 },
    location: "Gurugram, India",
    summary: "Monitor, detect, and respond to security incidents in a 24x7 SOC environment.",
    responsibilities: "Triage alerts; investigate incidents; maintain runbooks.",
    qualifications: "SOC experience; SIEM tooling; security certifications a plus.",
  },
  "SOC Analyst": {
    skills: ["siem", "log analysis", "incident response", "threat hunting"],
    experienceLevel: "junior",
    jobType: "full-time",
    workMode: "onsite",
    salary: { min: 700000, max: 1000000 },
    location: "Gurugram, India",
    summary: "Join a SOC team monitoring enterprise environments for threats and anomalies.",
    responsibilities: "Monitor security dashboards; escalate incidents; document findings.",
    qualifications: "1+ year security operations experience; strong attention to detail.",
  },
  "UI/UX Designer": {
    skills: ["figma", "prototyping", "user research", "design systems"],
    experienceLevel: "mid",
    jobType: "full-time",
    workMode: "hybrid",
    salary: { min: 1000000, max: 1500000 },
    location: "Bengaluru, India",
    summary: "Design clean, accessible product experiences for a modern recruitment platform.",
    responsibilities: "Own design process from research to handoff; maintain design system.",
    qualifications: "Strong portfolio; Figma expertise; experience shipping products.",
  },
  "QA Engineer": {
    skills: ["testing", "playwright", "jest", "cypress", "api testing"],
    experienceLevel: "mid",
    jobType: "full-time",
    workMode: "hybrid",
    salary: { min: 900000, max: 1300000 },
    location: "Chennai, India",
    summary: "Own quality for web products through automation, exploratory testing, and CI.",
    responsibilities: "Write automated tests; review requirements for testability; report defects.",
    qualifications: "Test automation experience; API testing; CI integration knowledge.",
  },
  "Product Manager": {
    skills: ["product strategy", "roadmapping", "stakeholder management", "analytics"],
    experienceLevel: "lead",
    jobType: "full-time",
    workMode: "hybrid",
    salary: { min: 2400000, max: 3400000 },
    location: "Bengaluru, India",
    summary: "Lead product discovery and delivery for a hiring platform serving thousands of teams.",
    responsibilities: "Define roadmap; gather requirements; ship and measure features.",
    qualifications: "5+ years product management; strong analytics and communication.",
  },
};

// Jobs: title + recruiter (email) + status + optional overrides.
// Active jobs only belong to verified recruiters (business rule respected).
const SEED_JOB_SPECS = [
  { title: "Frontend Developer", recruiterEmail: "recruiter.seed@opportunityx.local", status: "active", featured: true },
  { title: "React Developer", recruiterEmail: "recruiter.seed@opportunityx.local", status: "active" },
  { title: "MERN Developer", recruiterEmail: "recruiter.seed@opportunityx.local", status: "active", featured: true },
  { title: "Backend Developer", recruiterEmail: "recruiter.seed@opportunityx.local", status: "active" },
  { title: "Node.js Developer", recruiterEmail: "recruiter.seed@opportunityx.local", status: "active" },
  { title: "Full Stack Developer", recruiterEmail: "recruiter.seed@opportunityx.local", status: "active", featured: true },
  { title: "DevOps Engineer", recruiterEmail: "recruiter.seed@opportunityx.local", status: "active" },
  { title: "UI/UX Designer", recruiterEmail: "recruiter.seed@opportunityx.local", status: "active" },
  { title: "QA Engineer", recruiterEmail: "recruiter.seed@opportunityx.local", status: "active" },
  { title: "Product Manager", recruiterEmail: "recruiter.seed@opportunityx.local", status: "draft" },

  { title: "Java Developer", recruiterEmail: "recruiter02@opportunityx.local", status: "active" },
  { title: "Python Developer", recruiterEmail: "recruiter02@opportunityx.local", status: "active" },
  { title: "Data Analyst", recruiterEmail: "recruiter02@opportunityx.local", status: "active", featured: true },
  { title: "Cloud Engineer", recruiterEmail: "recruiter02@opportunityx.local", status: "active" },
  { title: "Backend Developer", recruiterEmail: "recruiter02@opportunityx.local", status: "active" },
  { title: "Frontend Developer", recruiterEmail: "recruiter02@opportunityx.local", status: "active" },
  { title: "Full Stack Developer", recruiterEmail: "recruiter02@opportunityx.local", status: "active" },
  { title: "QA Engineer", recruiterEmail: "recruiter02@opportunityx.local", status: "closed" },

  { title: "DevOps Engineer", recruiterEmail: "recruiter03@opportunityx.local", status: "active", featured: true },
  { title: "Cloud Engineer", recruiterEmail: "recruiter03@opportunityx.local", status: "active" },
  { title: "Security Engineer", recruiterEmail: "recruiter03@opportunityx.local", status: "active" },
  { title: "Data Analyst", recruiterEmail: "recruiter03@opportunityx.local", status: "active" },
  { title: "Node.js Developer", recruiterEmail: "recruiter03@opportunityx.local", status: "active" },
  { title: "MERN Developer", recruiterEmail: "recruiter03@opportunityx.local", status: "active" },
  { title: "Full Stack Developer", recruiterEmail: "recruiter03@opportunityx.local", status: "draft" },

  { title: "Java Developer", recruiterEmail: "recruiter04@opportunityx.local", status: "pending" },
  { title: "Python Developer", recruiterEmail: "recruiter04@opportunityx.local", status: "pending" },
  { title: "QA Engineer", recruiterEmail: "recruiter04@opportunityx.local", status: "pending" },
  { title: "Data Analyst", recruiterEmail: "recruiter04@opportunityx.local", status: "draft" },

  { title: "Frontend Developer", recruiterEmail: "recruiter05@opportunityx.local", status: "pending" },
  { title: "SOC Analyst", recruiterEmail: "recruiter05@opportunityx.local", status: "draft" },
  { title: "Cybersecurity Analyst", recruiterEmail: "recruiter05@opportunityx.local", status: "pending" },
];

// Applications: { candidateEmail, jobTitle, recruiterEmail, stage }.
// stage must be a valid PIPELINE_STAGE; legacy `status` auto-syncs on validate.
const SEED_APPLICATIONS = [
  // candidate01
  { candidateEmail: "candidate01@opportunityx.local", jobTitle: "MERN Developer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "interview_scheduled" },
  { candidateEmail: "candidate01@opportunityx.local", jobTitle: "Full Stack Developer", recruiterEmail: "recruiter03@opportunityx.local", stage: "shortlisted" },
  { candidateEmail: "candidate01@opportunityx.local", jobTitle: "Node.js Developer", recruiterEmail: "recruiter03@opportunityx.local", stage: "applied" },
  { candidateEmail: "candidate01@opportunityx.local", jobTitle: "Frontend Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "rejected" },
  { candidateEmail: "candidate01@opportunityx.local", jobTitle: "Full Stack Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "offer_accepted" },
  // candidate02
  { candidateEmail: "candidate02@opportunityx.local", jobTitle: "Frontend Developer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "interview_completed" },
  { candidateEmail: "candidate02@opportunityx.local", jobTitle: "React Developer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "shortlisted" },
  { candidateEmail: "candidate02@opportunityx.local", jobTitle: "UI/UX Designer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "applied" },
  { candidateEmail: "candidate02@opportunityx.local", jobTitle: "Frontend Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "assessment" },
  { candidateEmail: "candidate02@opportunityx.local", jobTitle: "MERN Developer", recruiterEmail: "recruiter03@opportunityx.local", stage: "rejected" },
  // candidate03
  { candidateEmail: "candidate03@opportunityx.local", jobTitle: "Backend Developer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "offer_sent" },
  { candidateEmail: "candidate03@opportunityx.local", jobTitle: "Node.js Developer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "screening" },
  { candidateEmail: "candidate03@opportunityx.local", jobTitle: "Backend Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "interview_scheduled" },
  { candidateEmail: "candidate03@opportunityx.local", jobTitle: "Python Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "screening" },
  { candidateEmail: "candidate03@opportunityx.local", jobTitle: "Java Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "rejected" },
  // candidate04
  { candidateEmail: "candidate04@opportunityx.local", jobTitle: "Data Analyst", recruiterEmail: "recruiter02@opportunityx.local", stage: "hired" },
  { candidateEmail: "candidate04@opportunityx.local", jobTitle: "Data Analyst", recruiterEmail: "recruiter03@opportunityx.local", stage: "interview_completed" },
  { candidateEmail: "candidate04@opportunityx.local", jobTitle: "QA Engineer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "shortlisted" },
  { candidateEmail: "candidate04@opportunityx.local", jobTitle: "Backend Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "applied" },
  { candidateEmail: "candidate04@opportunityx.local", jobTitle: "Full Stack Developer", recruiterEmail: "recruiter03@opportunityx.local", stage: "withdrawn" },
  // candidate05
  { candidateEmail: "candidate05@opportunityx.local", jobTitle: "Java Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "offer_accepted" },
  { candidateEmail: "candidate05@opportunityx.local", jobTitle: "Cloud Engineer", recruiterEmail: "recruiter02@opportunityx.local", stage: "interview_scheduled" },
  { candidateEmail: "candidate05@opportunityx.local", jobTitle: "Backend Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "screening" },
  { candidateEmail: "candidate05@opportunityx.local", jobTitle: "Full Stack Developer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "assessment" },
  { candidateEmail: "candidate05@opportunityx.local", jobTitle: "Java Developer", recruiterEmail: "recruiter04@opportunityx.local", stage: "applied" },
  // candidate06
  { candidateEmail: "candidate06@opportunityx.local", jobTitle: "UI/UX Designer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "offer_sent" },
  { candidateEmail: "candidate06@opportunityx.local", jobTitle: "Frontend Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "applied" },
  { candidateEmail: "candidate06@opportunityx.local", jobTitle: "React Developer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "screening" },
  { candidateEmail: "candidate06@opportunityx.local", jobTitle: "MERN Developer", recruiterEmail: "recruiter03@opportunityx.local", stage: "applied" },
  { candidateEmail: "candidate06@opportunityx.local", jobTitle: "QA Engineer", recruiterEmail: "recruiter02@opportunityx.local", stage: "rejected" },
  // candidate07
  { candidateEmail: "candidate07@opportunityx.local", jobTitle: "DevOps Engineer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "interview_completed" },
  { candidateEmail: "candidate07@opportunityx.local", jobTitle: "DevOps Engineer", recruiterEmail: "recruiter03@opportunityx.local", stage: "interview_scheduled" },
  { candidateEmail: "candidate07@opportunityx.local", jobTitle: "Cloud Engineer", recruiterEmail: "recruiter03@opportunityx.local", stage: "shortlisted" },
  { candidateEmail: "candidate07@opportunityx.local", jobTitle: "Cloud Engineer", recruiterEmail: "recruiter02@opportunityx.local", stage: "screening" },
  { candidateEmail: "candidate07@opportunityx.local", jobTitle: "Full Stack Developer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "applied" },
  // candidate08
  { candidateEmail: "candidate08@opportunityx.local", jobTitle: "MERN Developer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "screening" },
  { candidateEmail: "candidate08@opportunityx.local", jobTitle: "Frontend Developer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "applied" },
  { candidateEmail: "candidate08@opportunityx.local", jobTitle: "Full Stack Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "shortlisted" },
  { candidateEmail: "candidate08@opportunityx.local", jobTitle: "MERN Developer", recruiterEmail: "recruiter03@opportunityx.local", stage: "assessment" },
  { candidateEmail: "candidate08@opportunityx.local", jobTitle: "QA Engineer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "applied" },
  // candidate09
  { candidateEmail: "candidate09@opportunityx.local", jobTitle: "QA Engineer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "offer_accepted" },
  { candidateEmail: "candidate09@opportunityx.local", jobTitle: "QA Engineer", recruiterEmail: "recruiter02@opportunityx.local", stage: "interview_completed" },
  { candidateEmail: "candidate09@opportunityx.local", jobTitle: "Data Analyst", recruiterEmail: "recruiter03@opportunityx.local", stage: "applied" },
  { candidateEmail: "candidate09@opportunityx.local", jobTitle: "Frontend Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "rejected" },
  { candidateEmail: "candidate09@opportunityx.local", jobTitle: "DevOps Engineer", recruiterEmail: "recruiter03@opportunityx.local", stage: "applied" },
  // candidate10
  { candidateEmail: "candidate10@opportunityx.local", jobTitle: "Python Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "interview_scheduled" },
  { candidateEmail: "candidate10@opportunityx.local", jobTitle: "Python Developer", recruiterEmail: "recruiter04@opportunityx.local", stage: "applied" },
  { candidateEmail: "candidate10@opportunityx.local", jobTitle: "Data Analyst", recruiterEmail: "recruiter02@opportunityx.local", stage: "screening" },
  { candidateEmail: "candidate10@opportunityx.local", jobTitle: "Backend Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "applied" },
  { candidateEmail: "candidate10@opportunityx.local", jobTitle: "Full Stack Developer", recruiterEmail: "recruiter02@opportunityx.local", stage: "withdrawn" },
  // candidate11
  { candidateEmail: "candidate11@opportunityx.local", jobTitle: "Cloud Engineer", recruiterEmail: "recruiter02@opportunityx.local", stage: "hired" },
  { candidateEmail: "candidate11@opportunityx.local", jobTitle: "Cloud Engineer", recruiterEmail: "recruiter03@opportunityx.local", stage: "offer_sent" },
  { candidateEmail: "candidate11@opportunityx.local", jobTitle: "DevOps Engineer", recruiterEmail: "recruiter03@opportunityx.local", stage: "interview_completed" },
  { candidateEmail: "candidate11@opportunityx.local", jobTitle: "DevOps Engineer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "screening" },
  { candidateEmail: "candidate11@opportunityx.local", jobTitle: "Security Engineer", recruiterEmail: "recruiter03@opportunityx.local", stage: "shortlisted" },
  // candidate12
  { candidateEmail: "candidate12@opportunityx.local", jobTitle: "Cybersecurity Analyst", recruiterEmail: "recruiter05@opportunityx.local", stage: "applied" },
  { candidateEmail: "candidate12@opportunityx.local", jobTitle: "Security Engineer", recruiterEmail: "recruiter03@opportunityx.local", stage: "assessment" },
  { candidateEmail: "candidate12@opportunityx.local", jobTitle: "SOC Analyst", recruiterEmail: "recruiter05@opportunityx.local", stage: "applied" },
  { candidateEmail: "candidate12@opportunityx.local", jobTitle: "Frontend Developer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "rejected" },
  { candidateEmail: "candidate12@opportunityx.local", jobTitle: "Node.js Developer", recruiterEmail: "recruiter.seed@opportunityx.local", stage: "screening" },
];

// Interviews: reference an application by (candidateEmail, jobTitle, recruiterEmail).
const SEED_INTERVIEWS = [
  { candidateEmail: "candidate01@opportunityx.local", jobTitle: "MERN Developer", recruiterEmail: "recruiter.seed@opportunityx.local", title: "Technical Interview - MERN", stage: "technical", mode: "google_meet", status: "confirmed", daysAhead: 2, duration: 60, timezone: "Asia/Kolkata" },
  { candidateEmail: "candidate03@opportunityx.local", jobTitle: "Backend Developer", recruiterEmail: "recruiter.seed@opportunityx.local", title: "Backend System Design", stage: "technical", mode: "google_meet", status: "scheduled", daysAhead: 5, duration: 90, timezone: "Asia/Kolkata" },
  { candidateEmail: "candidate03@opportunityx.local", jobTitle: "Backend Developer", recruiterEmail: "recruiter02@opportunityx.local", title: "HR Round", stage: "hr", mode: "phone", status: "scheduled", daysAhead: 3, duration: 30, timezone: "Asia/Kolkata" },
  { candidateEmail: "candidate05@opportunityx.local", jobTitle: "Cloud Engineer", recruiterEmail: "recruiter02@opportunityx.local", title: "Cloud Architecture Discussion", stage: "managerial", mode: "microsoft_teams", status: "confirmed", daysAhead: 1, duration: 60, timezone: "Asia/Kolkata" },
  { candidateEmail: "candidate05@opportunityx.local", jobTitle: "Java Developer", recruiterEmail: "recruiter02@opportunityx.local", title: "Java Coding Round", stage: "technical", mode: "google_meet", status: "completed", daysAhead: -10, duration: 60, timezone: "Asia/Kolkata" },
  { candidateEmail: "candidate07@opportunityx.local", jobTitle: "DevOps Engineer", recruiterEmail: "recruiter.seed@opportunityx.local", title: "DevOps Technical Round", stage: "technical", mode: "zoom", status: "completed", daysAhead: -7, duration: 75, timezone: "Asia/Kolkata" },
  { candidateEmail: "candidate07@opportunityx.local", jobTitle: "DevOps Engineer", recruiterEmail: "recruiter03@opportunityx.local", title: "Kubernetes Deep Dive", stage: "technical", mode: "google_meet", status: "scheduled", daysAhead: 4, duration: 90, timezone: "Asia/Kolkata" },
  { candidateEmail: "candidate02@opportunityx.local", jobTitle: "Frontend Developer", recruiterEmail: "recruiter.seed@opportunityx.local", title: "Frontend Architecture Review", stage: "technical", mode: "google_meet", status: "completed", daysAhead: -14, duration: 60, timezone: "Asia/Kolkata" },
  { candidateEmail: "candidate04@opportunityx.local", jobTitle: "Data Analyst", recruiterEmail: "recruiter03@opportunityx.local", title: "SQL Case Study", stage: "technical", mode: "office", status: "completed", daysAhead: -6, duration: 60, timezone: "Asia/Kolkata" },
  { candidateEmail: "candidate10@opportunityx.local", jobTitle: "Python Developer", recruiterEmail: "recruiter02@opportunityx.local", title: "Python + Data Round", stage: "technical", mode: "google_meet", status: "cancelled", daysAhead: 0, duration: 60, timezone: "Asia/Kolkata", cancelledReason: "Candidate requested a date change." },
  { candidateEmail: "candidate11@opportunityx.local", jobTitle: "Cloud Engineer", recruiterEmail: "recruiter03@opportunityx.local", title: "Cloud Technical Round", stage: "technical", mode: "zoom", status: "rescheduled", daysAhead: 1, duration: 60, timezone: "Asia/Kolkata" },
  { candidateEmail: "candidate09@opportunityx.local", jobTitle: "QA Engineer", recruiterEmail: "recruiter02@opportunityx.local", title: "QA Automation Round", stage: "technical", mode: "google_meet", status: "no_show", daysAhead: -2, duration: 45, timezone: "Asia/Kolkata" },
];

// Saved jobs: { candidateEmail, jobTitle, recruiterEmail } — only active jobs.
const SEED_SAVED_JOBS = [
  { candidateEmail: "candidate01@opportunityx.local", jobTitle: "Frontend Developer", recruiterEmail: "recruiter.seed@opportunityx.local" },
  { candidateEmail: "candidate01@opportunityx.local", jobTitle: "DevOps Engineer", recruiterEmail: "recruiter03@opportunityx.local" },
  { candidateEmail: "candidate01@opportunityx.local", jobTitle: "Cloud Engineer", recruiterEmail: "recruiter02@opportunityx.local" },
  { candidateEmail: "candidate02@opportunityx.local", jobTitle: "MERN Developer", recruiterEmail: "recruiter.seed@opportunityx.local" },
  { candidateEmail: "candidate02@opportunityx.local", jobTitle: "Data Analyst", recruiterEmail: "recruiter02@opportunityx.local" },
  { candidateEmail: "candidate03@opportunityx.local", jobTitle: "Full Stack Developer", recruiterEmail: "recruiter.seed@opportunityx.local" },
  { candidateEmail: "candidate03@opportunityx.local", jobTitle: "Security Engineer", recruiterEmail: "recruiter03@opportunityx.local" },
  { candidateEmail: "candidate04@opportunityx.local", jobTitle: "QA Engineer", recruiterEmail: "recruiter.seed@opportunityx.local" },
  { candidateEmail: "candidate04@opportunityx.local", jobTitle: "Java Developer", recruiterEmail: "recruiter02@opportunityx.local" },
  { candidateEmail: "candidate05@opportunityx.local", jobTitle: "Cloud Engineer", recruiterEmail: "recruiter03@opportunityx.local" },
  { candidateEmail: "candidate05@opportunityx.local", jobTitle: "Backend Developer", recruiterEmail: "recruiter.seed@opportunityx.local" },
  { candidateEmail: "candidate06@opportunityx.local", jobTitle: "UI/UX Designer", recruiterEmail: "recruiter.seed@opportunityx.local" },
  { candidateEmail: "candidate06@opportunityx.local", jobTitle: "Full Stack Developer", recruiterEmail: "recruiter02@opportunityx.local" },
  { candidateEmail: "candidate07@opportunityx.local", jobTitle: "DevOps Engineer", recruiterEmail: "recruiter.seed@opportunityx.local" },
  { candidateEmail: "candidate07@opportunityx.local", jobTitle: "Cloud Engineer", recruiterEmail: "recruiter03@opportunityx.local" },
  { candidateEmail: "candidate08@opportunityx.local", jobTitle: "MERN Developer", recruiterEmail: "recruiter03@opportunityx.local" },
  { candidateEmail: "candidate08@opportunityx.local", jobTitle: "Frontend Developer", recruiterEmail: "recruiter02@opportunityx.local" },
  { candidateEmail: "candidate09@opportunityx.local", jobTitle: "QA Engineer", recruiterEmail: "recruiter02@opportunityx.local" },
  { candidateEmail: "candidate10@opportunityx.local", jobTitle: "Python Developer", recruiterEmail: "recruiter02@opportunityx.local" },
  { candidateEmail: "candidate11@opportunityx.local", jobTitle: "Security Engineer", recruiterEmail: "recruiter03@opportunityx.local" },
];

// Chat conversations (candidate <-> recruiter) with deterministic messages.
const SEED_CHATS = [
  {
    candidateEmail: "candidate01@opportunityx.local",
    jobTitle: "MERN Developer",
    recruiterEmail: "recruiter.seed@opportunityx.local",
    messages: [
      { from: "candidate", content: "Hi! Thanks for the opportunity. I'd love to discuss my experience with the MERN stack." },
      { from: "recruiter", content: "Hi Aarav, thanks for applying. Can you confirm your availability for a technical round this week?" },
      { from: "candidate", content: "Yes, I'm free on Thursday after 2 PM IST." },
      { from: "recruiter", content: "Great, I'll send a calendar invite shortly." },
      { from: "candidate", content: "Perfect, looking forward to it!" },
    ],
  },
  {
    candidateEmail: "candidate02@opportunityx.local",
    jobTitle: "Frontend Developer",
    recruiterEmail: "recruiter.seed@opportunityx.local",
    messages: [
      { from: "candidate", content: "Hello, I have attached my portfolio in my profile. Happy to walk you through it." },
      { from: "recruiter", content: "Your React work looks great! The team will review it today." },
      { from: "candidate", content: "Thank you! Let me know if you need any more details." },
      { from: "recruiter", content: "Will do. Expect an update by end of day." },
    ],
  },
  {
    candidateEmail: "candidate03@opportunityx.local",
    jobTitle: "Backend Developer",
    recruiterEmail: "recruiter.seed@opportunityx.local",
    messages: [
      { from: "recruiter", content: "Hi Rahul, we were impressed with your system design round." },
      { from: "candidate", content: "Thank you! I really enjoyed discussing the architecture." },
      { from: "recruiter", content: "We'd like to move you to the final offer stage. Is the salary range acceptable to you?" },
      { from: "candidate", content: "Yes, the range works for me. Excited to move ahead!" },
      { from: "recruiter", content: "Excellent, our team will draft the offer letter this week." },
    ],
  },
  {
    candidateEmail: "candidate05@opportunityx.local",
    jobTitle: "Java Developer",
    recruiterEmail: "recruiter02@opportunityx.local",
    messages: [
      { from: "candidate", content: "Hi Vikram, thanks for the smooth interview process." },
      { from: "recruiter", content: "You're welcome, Karan! We'd like to make you an offer." },
      { from: "candidate", content: "That's wonderful news, thank you!" },
      { from: "recruiter", content: "You'll receive the offer details in your email shortly." },
    ],
  },
  {
    candidateEmail: "candidate07@opportunityx.local",
    jobTitle: "DevOps Engineer",
    recruiterEmail: "recruiter03@opportunityx.local",
    messages: [
      { from: "recruiter", content: "Hi Aditya, scheduling your Kubernetes deep dive for Thursday." },
      { from: "candidate", content: "Thursday works for me in the morning." },
      { from: "recruiter", content: "Perfect, 10 AM IST confirmed." },
    ],
  },
  {
    candidateEmail: "candidate10@opportunityx.local",
    jobTitle: "Python Developer",
    recruiterEmail: "recruiter02@opportunityx.local",
    messages: [
      { from: "candidate", content: "Hello, I wanted to follow up on my application status." },
      { from: "recruiter", content: "Hi Kabir, our team is still reviewing candidates for this role." },
      { from: "candidate", content: "Understood, thanks for the update." },
    ],
  },
];

// Recruiter notes attached to applications.
const SEED_NOTES = [
  { candidateEmail: "candidate01@opportunityx.local", jobTitle: "MERN Developer", recruiterEmail: "recruiter.seed@opportunityx.local", content: "Seed note: Strong MERN experience, great communication during screening." },
  { candidateEmail: "candidate02@opportunityx.local", jobTitle: "Frontend Developer", recruiterEmail: "recruiter.seed@opportunityx.local", content: "Seed note: Excellent design sense; portfolio shows production-scale React work." },
  { candidateEmail: "candidate03@opportunityx.local", jobTitle: "Backend Developer", recruiterEmail: "recruiter.seed@opportunityx.local", content: "Seed note: Outstanding system design; ready for offer stage." },
  { candidateEmail: "candidate04@opportunityx.local", jobTitle: "Data Analyst", recruiterEmail: "recruiter02@opportunityx.local", content: "Seed note: Hired for the Data Analyst role. Onboarding scheduled." },
  { candidateEmail: "candidate05@opportunityx.local", jobTitle: "Java Developer", recruiterEmail: "recruiter02@opportunityx.local", content: "Seed note: Strong Java fundamentals; offer accepted." },
  { candidateEmail: "candidate06@opportunityx.local", jobTitle: "UI/UX Designer", recruiterEmail: "recruiter.seed@opportunityx.local", content: "Seed note: Portfolio reviewed, moving to offer." },
  { candidateEmail: "candidate07@opportunityx.local", jobTitle: "DevOps Engineer", recruiterEmail: "recruiter.seed@opportunityx.local", content: "Seed note: Great infra knowledge; completed technical round." },
  { candidateEmail: "candidate08@opportunityx.local", jobTitle: "Full Stack Developer", recruiterEmail: "recruiter02@opportunityx.local", content: "Seed note: Fresher with strong project work; shortlisted." },
  { candidateEmail: "candidate09@opportunityx.local", jobTitle: "QA Engineer", recruiterEmail: "recruiter.seed@opportunityx.local", content: "Seed note: Automation skills verified; offer accepted." },
  { candidateEmail: "candidate10@opportunityx.local", jobTitle: "Python Developer", recruiterEmail: "recruiter02@opportunityx.local", content: "Seed note: Scheduling technical round." },
  { candidateEmail: "candidate11@opportunityx.local", jobTitle: "Cloud Engineer", recruiterEmail: "recruiter03@opportunityx.local", content: "Seed note: Cloud architecture discussion went well." },
  { candidateEmail: "candidate12@opportunityx.local", jobTitle: "Security Engineer", recruiterEmail: "recruiter03@opportunityx.local", content: "Seed note: In assessment stage, promising candidate." },
];

// Parsed resume demo data (no external AI calls).
const SEED_PARSED_RESUMES = [
  { candidateEmail: "candidate01@opportunityx.local", atsScore: 88, experienceYears: 4, skills: ["react", "node.js", "mongodb", "express", "typescript"], techStack: ["mern", "docker"], resumeUrl: "https://cdn.opportunityx.local/resumes/candidate01.pdf", fileName: "aarav-sharma-resume.pdf", mimeType: "application/pdf" },
  { candidateEmail: "candidate02@opportunityx.local", atsScore: 82, experienceYears: 3, skills: ["react", "typescript", "css", "tailwindcss"], techStack: ["react", "next.js"], resumeUrl: "https://cdn.opportunityx.local/resumes/candidate02.pdf", fileName: "riya-verma-resume.pdf", mimeType: "application/pdf" },
  { candidateEmail: "candidate03@opportunityx.local", atsScore: 90, experienceYears: 5, skills: ["node.js", "express", "mongodb", "redis"], techStack: ["node", "postgres", "kafka"], resumeUrl: "https://cdn.opportunityx.local/resumes/candidate03.pdf", fileName: "rahul-mehta-resume.pdf", mimeType: "application/pdf" },
  { candidateEmail: "candidate05@opportunityx.local", atsScore: 85, experienceYears: 6, skills: ["java", "spring boot", "microservices", "aws"], techStack: ["java", "spring", "aws"], resumeUrl: "https://cdn.opportunityx.local/resumes/candidate05.pdf", fileName: "karan-patel-resume.pdf", mimeType: "application/pdf" },
  { candidateEmail: "candidate07@opportunityx.local", atsScore: 87, experienceYears: 5, skills: ["aws", "terraform", "kubernetes", "docker"], techStack: ["aws", "k8s", "terraform"], resumeUrl: "https://cdn.opportunityx.local/resumes/candidate07.pdf", fileName: "aditya-rao-resume.pdf", mimeType: "application/pdf" },
  { candidateEmail: "candidate08@opportunityx.local", atsScore: 74, experienceYears: 1, skills: ["react", "node.js", "mongodb", "express"], techStack: ["mern"], resumeUrl: "https://cdn.opportunityx.local/resumes/candidate08.pdf", fileName: "ishaan-gupta-resume.pdf", mimeType: "application/pdf" },
];

// Report demo records (model-only; reportGenerator.js is NOT executed).
const SEED_REPORTS = [
  { generatedByEmail: "admin.seed@opportunityx.local", type: "applications", format: "csv", fileUrl: "https://cdn.opportunityx.local/reports/applications-seed.csv" },
  { generatedByEmail: "admin.seed@opportunityx.local", type: "jobs", format: "xlsx", fileUrl: "https://cdn.opportunityx.local/reports/jobs-seed.xlsx" },
  { generatedByEmail: "admin.seed@opportunityx.local", type: "growth", format: "pdf", fileUrl: "https://cdn.opportunityx.local/reports/growth-seed.pdf" },
];

module.exports = {
  SEED_PASSWORD,
  SEED_ADMINS,
  SEED_RECRUITERS,
  SEED_CANDIDATES,
  SEED_ORGANIZATIONS,
  JOB_CATEGORIES,
  SEED_JOB_SPECS,
  SEED_APPLICATIONS,
  SEED_INTERVIEWS,
  SEED_SAVED_JOBS,
  SEED_CHATS,
  SEED_NOTES,
  SEED_PARSED_RESUMES,
  SEED_REPORTS,
};
