const ORGANIZATION_ROLES = Object.freeze({
  OWNER: "owner",
  ADMIN: "admin",
  RECRUITER: "recruiter",
  HIRING_MANAGER: "hiring_manager",
  INTERVIEWER: "interviewer",
  VIEWER: "viewer",
});

const ORGANIZATION_PERMISSIONS = Object.freeze({
  ORG_READ: "organization:read",
  ORG_UPDATE: "organization:update",
  ORG_DELETE: "organization:delete",
  MEMBERS_INVITE: "members:invite",
  MEMBERS_READ: "members:read",
  MEMBERS_UPDATE: "members:update",
  MEMBERS_REMOVE: "members:remove",
  OWNER_TRANSFER: "owner:transfer",
  BRANDING_UPDATE: "branding:update",
  SETTINGS_UPDATE: "settings:update",
  JOBS_CREATE: "jobs:create",
  JOBS_READ: "jobs:read",
  JOBS_UPDATE: "jobs:update",
  JOBS_DELETE: "jobs:delete",
  APPLICATIONS_READ: "applications:read",
  APPLICATIONS_UPDATE: "applications:update",
  INTERVIEWS_MANAGE: "interviews:manage",
  ANALYTICS_READ: "analytics:read",
});

const ROLE_PERMISSIONS = Object.freeze({
  [ORGANIZATION_ROLES.OWNER]: Object.values(ORGANIZATION_PERMISSIONS),
  [ORGANIZATION_ROLES.ADMIN]: Object.values(ORGANIZATION_PERMISSIONS).filter(
    (permission) => ![ORGANIZATION_PERMISSIONS.ORG_DELETE, ORGANIZATION_PERMISSIONS.OWNER_TRANSFER].includes(permission)
  ),
  [ORGANIZATION_ROLES.RECRUITER]: [
    ORGANIZATION_PERMISSIONS.ORG_READ,
    ORGANIZATION_PERMISSIONS.MEMBERS_READ,
    ORGANIZATION_PERMISSIONS.JOBS_CREATE,
    ORGANIZATION_PERMISSIONS.JOBS_READ,
    ORGANIZATION_PERMISSIONS.JOBS_UPDATE,
    ORGANIZATION_PERMISSIONS.APPLICATIONS_READ,
    ORGANIZATION_PERMISSIONS.APPLICATIONS_UPDATE,
    ORGANIZATION_PERMISSIONS.INTERVIEWS_MANAGE,
    ORGANIZATION_PERMISSIONS.ANALYTICS_READ,
  ],
  [ORGANIZATION_ROLES.HIRING_MANAGER]: [
    ORGANIZATION_PERMISSIONS.ORG_READ,
    ORGANIZATION_PERMISSIONS.MEMBERS_READ,
    ORGANIZATION_PERMISSIONS.JOBS_READ,
    ORGANIZATION_PERMISSIONS.JOBS_UPDATE,
    ORGANIZATION_PERMISSIONS.APPLICATIONS_READ,
    ORGANIZATION_PERMISSIONS.APPLICATIONS_UPDATE,
    ORGANIZATION_PERMISSIONS.INTERVIEWS_MANAGE,
    ORGANIZATION_PERMISSIONS.ANALYTICS_READ,
  ],
  [ORGANIZATION_ROLES.INTERVIEWER]: [
    ORGANIZATION_PERMISSIONS.ORG_READ,
    ORGANIZATION_PERMISSIONS.JOBS_READ,
    ORGANIZATION_PERMISSIONS.APPLICATIONS_READ,
    ORGANIZATION_PERMISSIONS.INTERVIEWS_MANAGE,
  ],
  [ORGANIZATION_ROLES.VIEWER]: [
    ORGANIZATION_PERMISSIONS.ORG_READ,
    ORGANIZATION_PERMISSIONS.JOBS_READ,
    ORGANIZATION_PERMISSIONS.APPLICATIONS_READ,
    ORGANIZATION_PERMISSIONS.ANALYTICS_READ,
  ],
});

const hasPermission = (role, permission) => Boolean(ROLE_PERMISSIONS[role]?.includes(permission));

module.exports = {
  ORGANIZATION_ROLES,
  ORGANIZATION_PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
};
